import React from 'react';
import Image from 'next/image';
import styled from 'styled-components';
import { Layout } from '@components/index';
import { formSet } from '@shared/styles/variable';

const Skills = () => {
  return (
    <Layout pageTitle="Skills" bgColor="bg-yellow" lineColor="yellow">
      <StContainer>
        <h3>Frontend</h3>
        <ul>
          <li>
            <Image
              alt="HTML-Logo"
              src="/images/skills/logo-html.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="CSS-Logo"
              src="/images/skills/logo-css.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="Styled-components-Logo"
              src="/images/skills/logo-sc.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="JS-Logo"
              src="/images/skills/logo-js.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="TS-Logo"
              src="/images/skills/logo-ts.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="React-Logo"
              src="/images/skills/logo-react.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="Recoil-Logo"
              src="/images/skills/logo-recoil.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="React-Query-Logo"
              src="/images/skills/logo-react-query.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="Nextjs-Logo"
              src="/images/skills/logo-nextjs.png"
              width={50}
              height={50}
            />
          </li>
        </ul>
      </StContainer>
      <StContainer>
        <h3>Version Control</h3>
        <ul>
          <li>
            <Image
              alt="Git-Logo"
              src="/images/skills/logo-git.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="GitHub-Logo"
              src="/images/skills/logo-github.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="GitLab-Logo"
              src="/images/skills/logo-gitlab.png"
              width={50}
              height={50}
            />
          </li>
        </ul>
      </StContainer>
      <StContainer>
        <h3>Mobile App</h3>
        <ul>
          <li>
            <Image
              alt="React-Native-Logo"
              src="/images/skills/logo-rn.png"
              width={50}
              height={50}
            />
          </li>
        </ul>
      </StContainer>
      <StContainer>
        <h3>Deployment</h3>
        <ul>
          <li>
            <Image
              alt="Vercel-Logo"
              src="/images/skills/logo-vercel.png"
              width={50}
              height={50}
            />
          </li>
        </ul>
      </StContainer>
      <StContainer>
        <h3>Communication</h3>
        <ul>
          <li>
            <Image
              alt="Jeplin-Logo"
              src="/images/skills/logo-jeplin.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="Figma-Logo"
              src="/images/skills/logo-figma.png"
              width={50}
              height={50}
            />
          </li>
          <li>
            <Image
              alt="Monday-Logo"
              src="/images/skills/logo-monday.png"
              width={50}
              height={50}
            />
          </li>
        </ul>
      </StContainer>
    </Layout>
  );
};

export default Skills;

const StContainer = styled.div`
  ${formSet()};
`;
