name: Test PR
on:
  pull_request:
    branches:
      - feature/github-workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Node.js Setting
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          yarn ci
          yarn lint
        env:
          CI: true
